### ISSUE TITLE
possibly dangerous cast

### ISSUE THREAD

**Issue by nmav** [ktls/af_ktls#14]
```
static void increment_seqno(char *s)
{
	u64 *seqno = (u64 *) s;
```

This cast's operation is cpu-specific. It works on intel arch but there are others that cannot cope with it.

**Comment by nmav** [comment]
The issue is that some CPU's cannot operate on non-aligned integers. So if the memory pointed by s is not 4 or 8-byte aligned you will get a crash on these cpus if you attempt to use that memory as integer.

**Comment by djwatson** [comment]
We could go the other way and align the u64, and cast down to u8. 

Alternatively, the openssl sources have a routine to just increment bytewise in bigendian instead of converting.  

Either of these are probably better than a memcpy

**Comment by djwatson** [comment]
fixed
