### ISSUE TITLE
Overflow in sendfile(2)

### ISSUE THREAD

**Issue by fridex** [ktls/af_ktls#2]
Using ```--sendfile``` in [AF_KTLS tool](https://github.com/fridex/af_ktls-tool) with a file which has more than 2GB causes overflow. This should be easyfix.

**Comment by djwatson** [comment]
This looks like a limit in sendfile itself.  At least in some versions of the manpage it states the limit:

http://man7.org/linux/man-pages/man2/sendfile.2.html
