### ISSUE TITLE
Avoid kernel_sendmsg()

### ISSUE THREAD

**Issue by fridex** [ktls/af_ktls#22]
Current implementation uses ```kernel_sendmsg()``` for sending records. This function does copy from passed vector, so it would be nice to avoid it.

There can be used ```kernel_sendpage()```, which operates directly on pages (see [1] for TCP, see [2] for UDP).

[1] http://lxr.free-electrons.com/source/net/ipv4/tcp.c#L1017
[2] http://lxr.free-electrons.com/source/net/ipv4/udp.c#L1216

**Comment by djwatson** [comment]
Here's the perf I'm getting: 80% is still in the helper_encrypt code, but a bit is still in sendmsg/recvmsg copying.

perf record -g ./client --sendfile file.txt --verbose --sendfile-size 10000000000  --server-host localhost --server-port 5555

![screen shot 2016-05-05 at 11 10 46 am](https://cloud.githubusercontent.com/assets/1105350/15052376/3dea3d7a-12b2-11e6-944d-247e329f860c.png)

**Comment by fridex** [comment]
I am getting:
  * 47.45% from total spent in ```rfc5288_encrypt```
    * 30% from total spent on actual encryption
    * 11.73% from total spent on copy - ```scatterwalk_map_and_copy```
    * 1.24% from total spent in ```kmalloc```
  * 17.32% from total spent in ```kernel_sendmsg()```
    * 7.72% form total in ```tcp_push_one``` (7% in actual transmit)
    * 4.23 from total in ```memcpy_erms```

So to sum it up, ideally we could get cca 13% better results when rfc5288 would be optimized and additional cca 4% when ```kernel_sendpage()``` would be used instead of ```kernel_sendmsg()```.  These numbers are ideal though, there will be different paths which could (probably) introduce different issues.

Transferred 1GB file, reported by ```perf report --sort=symbol```

**Comment by fridex** [comment]
According benchmarks available at [1] with optimizations mentioned above (with 17% saved in total), we would reach similar values that I got by using ```mmap(2)``` on a file and sending it via Gnu TLS.

BTW ```perf``` reports context switches not expensive at all.

http://209.132.179.123:5000/i7-4600U-2.10GHz/sendfile-file_100MB.bin-16000--tls/index.html

**Comment by djwatson** [comment]
I'm trying to repro your mmap + gnutls results, I'm seeing it only slightly faster than read+ssl write. 

Link is old and broken now.  You were comparing the following two commands? 

./client --sendfile-mmap
vs. 
./client --sendfile

?

**Comment by fridex** [comment]
> You were comparing the following two commands?
> ./client --sendfile-mmap
> vs.
> ./client --sendfile
> ?

Yes, exactly.

**Comment by fridex** [comment]
Closing, kernel_sendmsg() is not used now.
