### ISSUE TITLE
incorrect header length checks

### ISSUE THREAD

**Issue by nmav** [ktls/af_ktls#23]
At: https://github.com/fridex/af_ktls/blob/master/af_ktls.c#L1046
you do not check whether the data received are sufficient before starting reading the header.

**Comment by fridex** [comment]
Thanks! There should be also check whether TLS/DTLS record size based on header corresponds to size that was actually peeked.

**Comment by lancerchao** [comment]
This issue can be closed.

**Comment by fridex** [comment]
Fixed in https://github.com/ktls/af_ktls/pull/62
