### ISSUE TITLE
Asynchronous cache should propagate error

### ISSUE THREAD

**Issue by fridex** [ktls/af_ktls#26]
Asynchronous cache currently stores data if decryption and packet disassembling went well. If there is an error, the error is not reflected in asynchronous cache. This causes that asynchronous worker tries to decrypt and disassemble record every time a record is received even so there is wrong record on top of receiving queue.

This should be avoided by propagating error in asynchronous cache (e.g. negative number will signalize error, positive number number of bytes in cache, zero would mean free cache).

This should be OK from consistency POV since the asynchronous cache gets invalidated every time there is a ```setsockopt(2)``` call.

**Comment by fridex** [comment]
related: https://github.com/fridex/af_ktls/issues/9

**Comment by djwatson** [comment]
no more cache.  closing
