### ISSUE TITLE
Don't depend on af_alg

### ISSUE THREAD

**Issue by djwatson** [ktls/af_ktls#27]
If CONFIG_CRYPTO_USER_API=n, there are a bunch of errors building, because we are depending on af_alg things and we shouldn't be

WARNING: "af_alg_make_sg" [/home/davejwatson/local/af_ktls/af_ktls.ko] undefined!
WARNING: "af_alg_wait_for_completion" [/home/davejwatson/local/af_ktls/af_ktls.ko] undefined!

**Comment by fridex** [comment]
Nice catch, thanks! I don't like copying functionality, even so ```af_alg_wait_for_completion``` is straightforward. ```af_alg_make_sg``` is useful to be reused in AF_KTLS. What do you think about removing these (at least ```af_alg_make_sg```) from AF_ALG and placing it anywhere to make it more generous and not dependent on AF_ALG?

**Comment by djwatson** [comment]
For sending patches upstream, yes, refactor them.  For a separate module for now we'll probably have to copy

**Comment by lancerchao** [comment]
I think instead we should specify af_alg as a dependency.
