### ISSUE TITLE
tls_sendmsg should send partial data for TCP

### ISSUE THREAD

**Issue by djwatson** [ktls/af_ktls#29]
Currently tls_sendmsg does a size check:

`     
        if (size > KTLS_MAX_PAYLOAD_SIZE) {
                ret = -E2BIG;
                goto send_end;
        }
`

For tcp, we should be sending KTLS_MAX_PAYLOAD_SIZE bytes, and returning the number of bytes sent, or providing a socket buffer somehow. 

I think this is probably OK for UDP/DTLS though.  

The man page says it should be EMSGSIZE:

> If the message is too long to pass atomically through the underlying protocol, the error EMSGSIZE is returned, and the message is not transmitted.

**Comment by fridex** [comment]
> For tcp, we should be sending KTLS_MAX_PAYLOAD_SIZE bytes, and returning the number of bytes sent

Sounds reasonable to transparently assemble records from kvec (simply by iterating over scatter/gather array passed) so user space does not have to care about it. I don't like the buffer approach, is it really needed here?

Nevertheless, I would consider to send payload based on MTU set by ```setsockopt(2)``` (which is KTLS_MAX_PAYLOAD_SIZE by default) for both TLS and DTLS.

Return values have to be reviewed. To be honest, I did not give any special care to return values at all (https://github.com/fridex/af_ktls/issues/3)

**Comment by lancerchao** [comment]
OpenSSL[1] segments data into record buffers if size overflows.

[1] https://www.ibm.com/support/knowledgecenter/ssw_i5_54/apis/sslwrite.htm

**Comment by djwatson** [comment]
fixed by https://github.com/ktls/af_ktls/pull/62

**Comment by lancerchao** [comment]
Why is this closed? #62 fixes recv partial data. It hasn't changed send.

**Comment by fridex** [comment]
Reopening...

**Comment by djwatson** [comment]
implemented in https://github.com/ktls/af_ktls/pull/84
