### ISSUE TITLE
support poll

### ISSUE THREAD

**Issue by djwatson** [ktls/af_ktls#33]
Poll isn't currently supported\.  Related, it looks like recvmsg / sendmsg don't block in blocking mode.

**Comment by lancerchao** [comment]
A simple implementation would be to piggy-back off tsk->socket's poll e.g.
`static unsigned int tls_poll(struct file *file, struct socket *sock,
		      struct poll_table_struct *wait) {
	struct tls_sock *tsk;
	tsk = tls_sk(sock->sk);
	return tsk->socket->ops->poll(tsk->socket->file, tsk->socket, wait);`

**Comment by fridex** [comment]
I was thinking about the same approach. We have to keep in mind, that we are above TCP/UDP. E.g. for ```POLLERR``` we should consider even errors during decryption (etc).

For now it will be probably OK to return ENOTSUPP for unsupported cases IMHO.

Just to note regards ```POLLPRI``` in TCP -  there should be implemented OOB support in ```tcp_read_sock()``` once we switch to it (see #21).

**Comment by djwatson** [comment]
For writes, this approach should work fine.  For reads, tcp does the wakeup via the original sk_data_ready, so we would need to make sure we call it in the right places

**Comment by fridex** [comment]
A custom callback ```tls_data_ready``` just spawns a worker and calls the original ```sk_data_ready``` to wake up possibly waiting recipient. The issue here I see is the asynchronous decryption that can make ```poll(2)``` tricky to implement for some events.

**Comment by djwatson** [comment]
fixed by https://github.com/ktls/af_ktls/pull/62
