### ISSUE TITLE
Design MSG_DONTWAIT for AF_KTLS

### ISSUE THREAD

**Issue by fridex** [ktls/af_ktls#38]
There is still missing nonblocking socket support in ```sendmsg(2)``` by supplying MSG_DONTWAIT flag. It will need big reorganization in sources so before the work will be started, here is my proposed idea, I am open for discussion.

I don't see any differences in UDP/TCP (DTLS/TLS) now, so the implementation could be possibly shared.

Since we drop preallocation of pages optimization (no reasonable results to keep it), it should be easier to handle MSG_DONTWAIT as well. Each time there is a ```tls_sendmsg()``` or ```tls_sendpage()``` called, we will allocate pages for the TLS/DTLS record and we will not reuse them.

I see reasonable to spawn a kernel worker each time there is a nonblocking ```sendmsg(2)``` called and return to user space. Each socket will have its own **one** sending worker. We will have to copy supplied buffer to a queue before returning though. The pseudocode for ```tls_sendmsg()``` (the same applies to ```tls_sendpage()``` but with a page instead of buf, handling payload not covered):

```
plaintext_pages = allocate_pages()
copy_to_pages(buf, plaintext_pages)
data_queue_push(plaintext_pages)
queue_work()
return;
```

Here is a pseudocode of a worker:

```
plaintext_pages = data_queue_pop()
ciphertext_pages = allocate_pages()
encrypt(plaintext_pages, ciphertext_pages)
free_pages(plaintext_pages)
record = prepare_record(ciphertext_pages) // header creation
kernel_sendpage(record)
```

There can be also supplied ```splice(2)``` with SPLICE_F_NONBLOCK, so similar approach should be introduced for ```kernel_sendpage()```. The synchronization between ```kernel_sendpage()``` and ```kernel_sendmsg()``` should be explicit with implemented queue (which should be guarded) - first called, first served (user space should synchronize in special cases).

The queue of (plaintext) pages that are going to be sent can be implemented with the linked list available in the kernel. Just to note that the core part of the worker pseudocode can be reused even 
when there is a blocking send.

Any suggestions?

related: https://github.com/fridex/af_ktls/issues/4 https://github.com/fridex/af_ktls/issues/22

**Comment by djwatson** [comment]
I think we can do the encrypt work in the user thread.  The only time we need to use a kernel worker thread is if kernel_sendpage returns EAGAIN.  Otherwise we're doing needless context switches. 

Also we should probably respect the socket buffer size for how much we will buffer for sending

**Comment by fridex** [comment]
Based on discussion with @nmav, we could simplify this by simply probing if the sending would block on nonblocking bound socket before the encryption. If so, we can immediately return to user space with -EAGAIN, otherwise we can encrypt and send.

With this approach there will be no need to implement cache/worker.

**Comment by djwatson** [comment]
^ I think that assumes the underlying socket buffer size is at least 16k + overhead in size?

**Comment by fridex** [comment]
IMO it depends on a record size you want to send. Since we are in the kernel space, we could check it directly if it fits in the underlying buffer.

**Comment by djwatson** [comment]
implemented in https://github.com/ktls/af_ktls/pull/84
