### ISSUE TITLE
sendmsg doesn't work with multiple iovecs

### ISSUE THREAD

**Issue by djwatson** [ktls/af_ktls#42]
In tls_sendmsg, if msghdr *msg contains more than one iovec, we only send the first one, assuming it contains all the data.  

af_alg_make_sg only copies a single iovec at a time, and we need to inspect the return value to see how much it copied.

**Comment by fridex** [comment]
Will have to look at this. There is called ```iov_iter_get_pages()```  [2] in ```af_alg_make_sg()``` [1]. 

[1] http://lxr.free-electrons.com/source/crypto/af_alg.c#L394
[2] http://lxr.free-electrons.com/source/lib/iov_iter.c#L591

**Comment by fridex** [comment]
It would worth to extend https://github.com/fridex/af_ktls-tool --verify-transmission with such test case.

**Comment by lancerchao** [comment]
recvmsg does not work with multiple iovecs either, though I think a patch similar to https://github.com/lancerchao/af_ktls/commit/62443b8d2a76b992fdb951880d7c59f8e9945465 would work

**Comment by fridex** [comment]
Fixed with https://github.com/ktls/af_ktls/commit/8d4c5232af6a90200c0198ed86549b6e199b7a19 and https://github.com/ktls/af_ktls/commit/3327bba1219491a909b80640745cf24e48f19d9e (#45 #57)
