### ISSUE TITLE
kernel fault when decrypting to user buffer

### ISSUE THREAD

**Issue by lancerchao** [ktls/af_ktls#56]
If a client makes a syscall like this:
```
char recv_mem[1000];
recv(fd, recv_mem, TLS_MAX_PAYLOAD_LENGTH, 0);
```
And the decryption is done straight to user memory (the else{} in tls_recvmsg) a kernel fault is triggered
http://pastebin.com/XjGu0dHx

**Comment by fridex** [comment]
I suppose that it occurs with TLS.

**Comment by lancerchao** [comment]
The kernel has to validate user buffers before accessing them. copy_page_to_iter does this for you, but the decryption api does not.

**Comment by lancerchao** [comment]
Tests available here.
https://github.com/ktls/af_ktls-test/blob/a84cbb8749505c0747859abe9e8c7c1a9ccb6416/tests.cpp#L483-L561

**Comment by fridex** [comment]
why was this issue closed?

**Comment by lancerchao** [comment]
Patch is available here. 
[https://github.com/lancerchao/af_ktls/commit/fe9c547c39a46587324aabcee2894571b3897849]

Btw, it is not necessary in ktls with revamped buffer management since those keep decrypted data in skbuffs and never decrypts straight to user memory.

**Comment by fridex** [comment]
I will take a look at your implementation ASAP.

Not to forget about this, reopening since fix is not available in ktls/af_ktls master.

**Comment by djwatson** [comment]
Fixed, no longer needed now that using skbs
