### ISSUE TITLE
Allocating too many pages

### ISSUE THREAD

**Issue by lancerchao** [ktls/af_ktls#65]
https://github.com/ktls/af_ktls/blob/7fbe182f62265af74c7d5c043eb19dba014aeeaf/af_ktls.c#L1731

alloc_pages allocates 1 << order number of pages. That line would therefore allocate 16 pages. 

Ref:
http://www.makelinux.net/books/lkd2/ch11lev1sec3

**Comment by fridex** [comment]
Fixed in https://github.com/ktls/af_ktls/pull/70
